### PR TITLE
Missing closing dbl quote on href

### PR DESCRIPTION
**Pull request by damonsk**

### CODE REVIEW

**Comment by mrainess** [comment]
Damon,

Maybe you can answer a question for me:

I did "git clone git://github.com/PrestaShop/PrestaShop.git"

Then to update I do "cd PrestaShop, git pull --commit"

This is not giving me the development branch. I get the master branch.

Doing "git branch" I see "\* master".

How can I get read-only access to the development branch?

I'm just learning git; so, if this is a stupid question, please forgive me.

Thanks,

Mark Rainess
<410-701-0736>

**Comment by damonsk** [comment]
try the following 

cd PrestaShop

git init

git checkout -b development

git pull origin development

That should be it I think.

**Comment by mrainess** [comment]
Damon,

I did "git clone git://github.com/PrestaShop/PrestaShop.git -b development",
and that seemed to work; "git branch" shows "\* development".

However; doing

"diff -rq --exclude *.svn PrestaShop/ current_SVN_development/"

shows over 2000 files that do not match.

What's going on?

Mark

On Fri, Nov 23, 2012 at 10:34 AM, Damon Skelhorn
notifications@github.comwrote:

> try the following
> 
> cd PrestaShop
> 
> git init
> 
> git checkout -b development
> 
> git pull origin development
> 
> That should be it I think.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/heskethm/Prestashop-Theme-Boilerplate/pull/16#issuecomment-10662771.

## 

Mark
Google Voice 410-701-0736

**Comment by damonsk** [comment]
Not too sure what you're aiming to do but everything within your PrestaShop is the development folder.  There won't be any sub folders such as current_SVN_development

**Comment by mrainess** [comment]
Damon,

I do not expect an svn folder inside the git repository. I was comparing
the fresh git repository to the last svn development repository. I expect
the differences between these to be small. They should be only the
changeswhich have been committed to the git repository but are not in
the old svn
repository. I am using this as a sanity check to make sure I've got git
figured out.

I've just done this:

sudo git clone git://github.com/PrestaShop/PrestaShop.git
cd PrestaShop
git branch
- master
  git branch -r
  origin/HEAD -> origin/master
  origin/development
  origin/master
  sudo git checkout development
  git branch
- development
  master

But, I find--using my sanity check--that the files still do not compare
properly to the old svn repository. I think I need another command to update
the working copy to the development branch. I'm working on it trying to
figure it out.

Mark

On Fri, Nov 23, 2012 at 11:41 AM, Damon Skelhorn
notifications@github.comwrote:

> Not too sure what you're aiming to do but everything within your
> PrestaShop is the development folder. There won't be any sub folders such
> as current_SVN_development
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/heskethm/Prestashop-Theme-Boilerplate/pull/16#issuecomment-10664538.

## 

Mark
Google Voice 410-701-0736

**Comment by damonsk** [comment]
This commit (https://github.com/PrestaShop/PrestaShop/commit/a1db83ef41636029a1ff431362deabbb3e8d0793) will be the reason why you're seeing so many unmatched files.

Since moving from svn to git they updated the code to remove svn specific information.

**Comment by mrainess** [comment]
Damon,

Thank you.

diff -rq --exclude *.svn --ignore-matching-lines="@version" PrestaShop/
ps_1.5_trunk/ | cat -n

Shows only 79 files that differ. Without ignore "@version"  it is 2014.
Makes me feel all warm and fuzzy.

Mark

On Fri, Nov 23, 2012 at 12:27 PM, Damon Skelhorn
notifications@github.comwrote:

> This commit (PrestaShop/PrestaShop@a1db83ehttps://github.com/PrestaShop/PrestaShop/commit/a1db83ef41636029a1ff431362deabbb3e8d0793)
> will be the reason why you're seeing so many unmatched files.
> 
> Since moving from svn to git they updated the code to remove svn specific
> information.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/heskethm/Prestashop-Theme-Boilerplate/pull/16#issuecomment-10665696.

## 

Mark
Google Voice 410-701-0736

**Pull request merged**
