### PR TITLE
New version running on Sass/Compass and Frameless grid

### PR DESCRIPTION
**Pull request by Evanion**
Here is a start of a Sass based design built with compass and the frameless responsive gridsystem. 

Frameless doesn't depend on any markup classes, but is entirely done in css with sass functions and mixins.

This commit have a lot of current css stripped or deactivated. Most preexisting css will need to be sassyfied (http://css2sass.heroku.com/ is a good tool for that). I will continue too work on this fork, but wanted to present it too you as a proposition for the way forward.

I would also propose a rename of the project to something shorter and easier too remember, like 'prestaplate'. ;)

### CODE REVIEW

**Comment by Evanion** [comment]
Ow, this should not be merged in to master as it's not presentable at the current stage. I Propose it gets merged to a devel branch.

**Comment by markahesketh** [comment]
Hey Mikael,

Thanks for your efforts :)

I'll get this merged into a branch once I'm back on my mac and have a look.

I've actually been doing a load of work on this on a local branch to try and get a 'baseline' theme ready for everyone to contribute, working with the CSS as well as overriding modules to use HTML5 markup.

What I've done so far is in LESS using SemanticGS (http://semantic.gs/), my only issue with Frameless is that its a fixed-width grid. I'll have to get everything on GitHub very soon as I know I've not pushed any commits for some time!

As for the name, funny you should say that as Prestaplate is what I'd originally planned on naming it, but didn't know if the -plate bit would make sense to some?

**Comment by markahesketh** [comment]
I've merged your changes to a new branch :) - https://github.com/heskethm/Prestashop-Theme-Boilerplate/tree/sass-frameless

I've also branched my recent LESS/Semantic GS/Module Override changes - https://github.com/heskethm/Prestashop-Theme-Boilerplate/tree/less-styles

Would really appreciate if you could take a look and give me your opinion, I've not styled/overridden the header or footer yet so I comment them out locally, but hopefully you'll be able to see what I've been doing.

**Comment by Evanion** [comment]
I'll take a look at it.

**Comment by Evanion** [comment]
Closing this pull request as it is merged.

**Pull request closed without merging**
